name: Release

on:
  push:
    tags: [ 'v*' ]   # triggers on git tags like v1.0.0

jobs:
  api-gateway:
    uses: ./.github/workflows/reusable-image.yml
    with:
      service: api-gateway
      tag: ${{ github.ref_name }}
    secrets: inherit

  user-service:
    uses: ./.github/workflows/reusable-image.yml
    with:
      service: user-service
      tag: ${{ github.ref_name }}
    secrets: inherit

  product-service:
    uses: ./.github/workflows/reusable-image.yml
    with:
      service: product-service
      tag: ${{ github.ref_name }}
    secrets: inherit

  order-service:
    uses: ./.github/workflows/reusable-image.yml
    with:
      service: order-service
      tag: ${{ github.ref_name }}
    secrets: inherit
